### ISSUE TITLE
[Question] How to pass params when navigate between miniApps

### ISSUE THREAD

**Issue by tranducduong1994** [electrode-io/movies-reloaded-miniapp#20]
Hello,

I saw this document: https://www.electrode.io/ern-navigation/Component.html#navigate
Function: navigate( route ) 
route | Object | The route object that details where to navigate next.

What is exactly object shape of route ?
Thanks you very much

**Comment by friederbluemle** [comment]
Hi @tranducduong1994 - You can find the structure of the `ErnNavRoute` object in schema.json:
https://github.com/electrode-io/ernnavigation-api/blob/master/schema.json#L127

There's also a small example in the project's readme file:
https://github.com/electrode-io/ernnavigation-api#readme

```
EnNavigationApi.requests().navigate({
  path: `${appName}_Page2`
}).then((e) => {
  console.log('Navigation Succeeded: ', e)
}).catch((e) => {
  console.error('Navigation Failed: ', e)
});
```

**Comment by tranducduong1994** [comment]
hello @friederbluemle :
"path" property is exactly "initialScreen" property when I create a AppNavigator ?
For example: MiniApp A
```
const appNavigator = new AppNavigator(
  {
    MiniAppA: App,
  },
  {
    initialScreen:'MiniAppA',
  },
);

appNavigator.registerAll('MiniAppA');
```
in MiniApp B, if I want to navigate to MiniApp A, i have to use navigate below ?:
```
this.navigate({
      path: 'MiniAppA',
    });
```
